from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from expnote.db import read_config, row_to_dict, transaction

MANAGED_START = "<!-- expnote:managed:start -->"
MANAGED_END = "<!-- expnote:managed:end -->"


def sync_markdown(root: Path) -> dict[str, Any]:
    config = read_config(root)
    notes_dir = root / config["notes_dir"]
    moc_path = root / config["moc_path"]
    notes_dir.mkdir(parents=True, exist_ok=True)
    moc_path.parent.mkdir(parents=True, exist_ok=True)

    with transaction(root) as conn:
        topics = [
            row_to_dict(row)
            for row in conn.execute(
                """
                SELECT * FROM topics
                WHERE deleted_at IS NULL
                ORDER BY created_at DESC, title DESC
                """
            )
        ]
        runs_by_topic: dict[str, list[dict[str, Any]]] = {}
        for topic in topics:
            runs_by_topic[topic["id"]] = [
                row_to_dict(row)
                for row in conn.execute(
                    """
                    SELECT * FROM runs
                    WHERE topic_id = ? AND deleted_at IS NULL
                    ORDER BY started_at ASC, id ASC
                    """,
                    (topic["id"],),
                )
            ]

    moc_content = _render_moc(topics, runs_by_topic)
    _write_managed_file(moc_path, moc_content)

    written_runs = 0
    for runs in runs_by_topic.values():
        for run in runs:
            run_path = notes_dir / f"{_safe_filename(run['id'])}.md"
            _write_managed_file(run_path, _render_run_note(run))
            written_runs += 1

    return {"moc": str(moc_path), "run_notes": written_runs}


def _render_moc(
    topics: list[dict[str, Any]],
    runs_by_topic: dict[str, list[dict[str, Any]]],
) -> str:
    lines = [
        "# Experiment MOC",
        "",
        "This section is generated by expnote. Write long-form analysis in run notes.",
        "",
    ]
    for topic in topics:
        lines.extend([f"## {topic['title']}", ""])
        if topic["summary"]:
            lines.extend([topic["summary"], ""])
        lines.extend(
            [
                "| # | run | purpose | relation | result | status |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for index, run in enumerate(runs_by_topic.get(topic["id"], []), start=1):
            lines.append(
                "| "
                + " | ".join(
                    [
                        str(index),
                        f"[[{run['id']}]]",
                        _cell(run["purpose"]),
                        _cell(run["relation"]),
                        _cell(run["result"]),
                        _cell(run["status"]),
                    ]
                )
                + " |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_run_note(run: dict[str, Any]) -> str:
    metadata = run.get("metadata", {})
    lines = [
        f"# {run['id']}",
        "",
        f"- status: `{run['status']}`",
        f"- started_at: `{run['started_at']}`",
        "",
        "## Purpose",
        "",
        run["purpose"] or "_TBD_",
        "",
        "## Relation",
        "",
        run["relation"] or "_TBD_",
        "",
        "## Result",
        "",
        run["result"] or "_TBD_",
        "",
        "## Metadata",
        "",
    ]
    if metadata:
        lines.extend(f"- `{key}`: {value}" for key, value in sorted(metadata.items()))
    else:
        lines.append("_No metadata recorded._")
    lines.extend(["", "## Analysis", "", "Write analysis here."])
    return "\n".join(lines).rstrip() + "\n"


def _write_managed_file(path: Path, managed_content: str) -> None:
    managed_block = f"{MANAGED_START}\n{managed_content}{MANAGED_END}\n"
    if not path.exists():
        path.write_text(managed_block, encoding="utf-8")
        return
    existing = path.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(MANAGED_START) + r".*?" + re.escape(MANAGED_END) + r"\n?",
        re.DOTALL,
    )
    if pattern.search(existing):
        updated = pattern.sub(managed_block, existing, count=1)
    else:
        updated = managed_block + "\n" + existing
    path.write_text(updated, encoding="utf-8")


def _cell(value: str) -> str:
    return (value or "").replace("\n", "<br>").replace("|", "\\|")


def _safe_filename(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("_") or "run"
